### ISSUE TITLE
Consider swapping order of inputs and ports

### ISSUE THREAD

**Issue by agoscinski** [C2SM/Sirocco#129]
PR #125 introduced ports for inputs in a shell task. This allows the user to specify how the arguments are passed to the command. These ports can can have a many to one mapping (e.g. `command {PORT::result}` could be resolved to `command result_1 result_2`) which is required because of the parametrized data nodes that are then gathered. This allows parameters to passed like this

```yaml
# cycle task
inputs:
  - x
      port: some_port
  - y
      port: some_port

#tasks
command: "command {PORT::some_port}" # will be resolved to `command x y`


data:
  # ...
  - x
```

We decided to make the ports nonoptional because otherwise the user would need to learn some default behavior. This way it the config file is self explanatory. This lead us to the question if we should not swap inputs and ports since it simplifies writing the file
```yaml
# cycle task
ports:
  - some_port:
      inputs:
        - x
        - y 
```
This has however the disadvantage that `inputs` lies not anymore in the same level as `outputs` which feels unintuitive reading such a file the first time. Therefore one suggestion was to swap also the name for ports with inputs. In this case it would make more sense to use for inputs the term `data` since they these objects are defined in the data section
```yaml
# cycle task
inputs:
  - some_input:
      data:
        - x
        - y
#tasks
command: "command {INPUT::some_input}" # will be resolved to `command x y`

data:
  # ...
  - x

```
