### ISSUE TITLE
Ports not correctly resolved when `when` is specified

### ISSUE THREAD

**Issue by agoscinski** [C2SM/Sirocco#140]
Currently the small use case results in the start date in the command options
```yaml
--restart  --init {initial_conditions} --forcing {forcing}
```
Specification in config.yml
```yaml
      command: "icon.py --restart {PORT::restart} --init {PORT::init}"
```
This due to the specification of when
```yaml
              - icon_restart:
                  when:
                    after: *root_start_date
                  target_cycle:
                    lag: -P2M
                  port: restart
```
This should not be as an option without args could result in an error.
