### ISSUE TITLE
`arg_option` should be a property of the task

### ISSUE THREAD

**Issue by leclairm** [C2SM/Sirocco#30]
Having the `arg_option` as a property of the task input data in the cycle description deviates from the design where the cycles are made of references to task and data nodes. `arg_option` would then be used for certain data nodes only when referenced as input data but not output data. I propose that this specification goes to the task description, looking like this for the small config example (keeping in mind that icon does not take arg options but it's not essential here):
```yaml
---
start_date: 2026-01-01T00:00
end_date: 2026-06-01T00:00
cycles:
  - bimonthly_tasks:
      period: P2M
      tasks:
        - icon:
            inputs:
              - icon_restart:
                  lag: -P2M
            outputs:
              - icon_output
              - icon_restart
  - lastly:
      tasks:
        - cleanup:
            depends:
              - icon:
                  date: 2026-05-01T00:00
tasks:
  - icon:
      plugin: shell
      command: $PWD/tests/files/scripts/icon.py
      input_arg_options:
        restart: --restart
  - cleanup:
      plugin: shell
      command: $PWD/tests/files/scripts/cleanup.py
data:
  available:
     - icon_input:
         type: file
         src: $PWD/tests/files/data/input
  generated:
     - icon_output:
         type: file
         src: output
     - icon_restart:
         type: file
         src: restart
```
This can be part of #23
