### ISSUE TITLE
Parametrized tasks and data

### ISSUE THREAD

**Issue by leclairm** [C2SM/Sirocco#44]
# Parameterized tasks

This issue comes earlier than planned because it has implications on the [design of `core.Store`](https://github.com/C2SM/Sirocco/wiki/Architectural-Decisions-Record#siroccocorestore-design), which is also the case for #40. #43 started as the implementation of #40 but then the idea arose to, at least, have the foundations ready for parameterized tasks and data. It could well end up being a full implementation of it.

The goal is to add arbitrary parameters to tasks and data so that Sirocco can be used for easily setting up typical parameterized experiments like ensemble simulations or sensitivity analysis, where the same task is reproduced with varying parameters. In the ICON case, these parameters would correspond to namelist parameters and one actual task per parameters combination would be generated.

## Parameters declaration
We suggest to declare parameters in a new dedicated top level `parameters` section of the configuration file. Each parameter should map a string to a sequence.
parameter keys are then referenced in corresponding task and data definitions.
```yaml
cycles:
  [...]
tasks:
  - icon:
      parameters: [random_seed, nml_param_name]
      [...]
  [...]
data:
  available:
    [...]
  generated:
    - icon_restart:
        parameters: [random_seed, nml_param_name]
        [...]
    [...]
parameters:
  random_seed: [0, 1, 2, 3, 4, 5]
  nml_param_foo: [1.25, 2.34, 0.49]
```
Possible extension: Allow for ranges using [`numpy.arrange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)
in order to avoid typing long lists
```yaml
parameters:
  random_seed: {'arange': [0, 100]}
  nml_param_foo: {'arange': [1.25, 2.1, 0.25]}
```

## Targetting parameterized taks and data in the graph specification
Adding parameters to tasks and data makes the linking of corresponding nodes ambiguous. In order to specify which parameters should be taken into account, we suggest to
introduce the same `parameters` key in the `cycles` section of the configuration file for input data and wait on tasks.
Each entry of `parameters` needs to map the name of a parameter to either `'all'` or `'single'`.
- `'all'` means link to all the target nodes along that parameter *axis*
- `'single'` means inherit from the referenced parameter and link to the corresponding target(s) (can still be multiple nodes if another parameter is marked as `'all'`).
- non-specified parameters when targetting parameterized tasks or data are marked as `'all'` by default. 

The following configuration file shows a full example of parameters declaration and references
```yaml
cycles:
  - icon_bimonthly:
      start_date: *root_start_date
      end_date: *root_end_date
      period: 'P2M'
      tasks:
        - icon:
            inputs:
              - icon_restart:
                  [...]
                  parameters:
                    random_seed: 'single'
                    nml_param_foo: 'single'
              [...]
            [...]
        [...]
  [...]
tasks:
  - icon:
      parameters: [random_seed, nml_param_name]
      [...]
  [...]
data:
  available:
    [...]
  generated:
    - icon_restart:
        parameters: [random_seed, nml_param_name]
        [...]
    [...]
parameters:
  random_seed: [0, 1, 2, 3, 4, 5]
  nml_param_foo: [1.25, 2.34, 0.49]
```

## Consistency rules
It should be checked, either at parsing time or early in the dependency resolving algorithm, that:
- outputs of a parameterized task share the same parameters with the said task.
- A task marking a parameter as `single` in the graph description (either for an input data node or a wait on task) must also have this parameter declared in its own description in the `tasks` section.
