### ISSUE TITLE
CLI arguments problem in distinguishing strings and data nodes

### ISSUE THREAD

**Issue by agoscinski** [C2SM/Sirocco#73]
Hello @leclairm, @GeigerJ2  and me started to look at the cli_arguments again and we have a design question. The problem in supporting a non data node in the cli arguments as in this example
```yaml
cli_arguments:
  positional:
    - not_a_data_node
    - data_node
...
data:
  available:
    - data_node:
      ...

# --> command not_a_data_node {data_node}
```
is that we need to check if `not_a_data_node` is in data or not to know how to interpret it internally. This could cause the problem that a user uses the name of names a data node the same as a string in the cli_arguments. This will result in an error which will be hard to debug for the user, we therefore would like to avoid this.

The suggestion we had during the meeting to put it to the flags leaves the question open how to handle the same problem positional arguments where the order matters

```yaml
cli_arguments:
  positional:
    - data_node
  flags:
    - not_a_data_node
    
...
data:
  available:
    - data_node:
      ...

# --> command data_node not_a_data_node
# or command not_a_data_node data_node
# Ambiguous!
```

One solution would be do also specify strings as data nodes
```yaml
cli_arguments:
  positional:
    - not_a_data_node
    - data_node
...
data:
  available:
    - not_a_data_node:
        value: not_a_data_node
        type: str
    - data_node:
      ...

# --> command {not_a_data_node} {data_node}
```
This however is a bit cumbersome to write. We therefore iterated to marking the data node somehow. Most naturally the string interpolation notation came from Python (and similar in other languages) came up
```yaml
cli_arguments:
  positional:
    - not_a_data_node
    - {data_node}
...
data:
  available:
    - data_node:
      ...

# --> command not_a_data_node {data_node}
```
But if we already need to use such a notation to mark data nodes then we could also simplify this using one string for the `cli_arguments`

```yaml
cli_arguments: "-ps1 --option {another_data_node} --ps 2  not_a_data_node {data_node}"
# --> command -ps1 --option {another_data_node} --ps 2 not_a_data_node {data_node}
```
It seems also the most intuitive for the user as one writes it like in the terminal. It is basically string interpolation, a concept from  programming languages the user might have seen already so this notation might be already intuitive. We were only worried that during parsing of this string we could run into behavior that is hard to debug but it seems so far that the parsing is very simple, thus there is not much room for errors to appear. See
```python
# splits whitespaces and removes redundant ones
# e.g. "a  {b}" --> ["a", "{b}"]
strings = [string for string in string.split(" ") if string != '']
for string in strings:
    if string.startswith("{") and string.endswith("}"):
        # check if string is in data nodes, if not raise error
```

**Comment by leclairm** [comment]
Thanks @agoscinski @GeigerJ2 
I quite like this proposition actually. We could even go one step further and put everything in the `command` item like
```yaml
tasks:
  - my_postproc:
      src: postproc/my_script.sh
      command: "./my_script.sh --verbosity 3 --input {data_1}"
```

**Comment by agoscinski** [comment]
@leclairm Wouldn't it then be?
```yaml
tasks:
  - my_postproc:
      src: postproc
      command: "./my_script.sh --verbosity 3 --input {data_1}"
# folder structure is postproc/my_script.sh, but potentially could contain more
```
So we copy (or link to) the whole folder and specify the script relative to the src folder
